tap "homebrew/core"
tap "homebrew/bundle"
tap "homebrew/services"
tap "homebrew/cask-versions"
tap "homebrew/cask-fonts"
tap "wix/brew"
brew "applesimutils"
brew "cocoapods"
brew "ffmpeg"
brew "gpg"
brew "nmap"
brew "stow"
brew "thefuck"
brew "youtube-dl"
brew "zsh"
brew "zsh-syntax-highlighting"
brew "z"
cask "1password"
cask "android-studio"
cask "audirvana"
cask "authy"
cask "calibre"
cask "charles"
cask "discord"
cask "docker-edge"
cask "firefox-developer-edition"
cask "font-hack"
cask "gas-mask"
cask "google-chrome"
cask "google-cloud-sdk"
cask "gpg-suite"
cask "imageoptim"
cask "iterm2"
cask "keybase"
cask "postico"
cask "postman"
cask "psequel"
cask "react-native-debugger"
cask "slack"
cask "visual-studio-code"
mas "tweetbot", id: 1384080005
mas "reeder", id: 1449412482
mas "numbers", id: 409203825
mas "pages", id: 409201541
mas "keynote", id: 409183694
mas "the-unarchiver", id: 425424353
